In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
import numpy as np # used for handling numbers
import pandas as pd # used for handling the dataset

In [ ]:
# data = pd.read_csv('/content/drive/MyDrive/Major_Project/Codebase/training/labeled_preprocessed_training.csv', encoding='utf-8')

In [ ]:
# data

,id,text,source,label,cleaned_text_1,cleaned_text_2
0,1,at 50 votes i will close this survey and take ...,twitter,0,50 votes close survey take new photos,at 50 votes i will close this survey and take ...
1,2,"21st birthday and nearly 4 months pregnant, no...",twitter,1,21st birthday nearly 4 months pregnant,21st birthday and nearly 4 months pregnant no
2,3,@_DudeThePie // I'd be killed. He's literally ...,twitter,0,killed literally 10th picture https,i be killed he literally my 10th picture https
3,4,"This year I'm gonna become a mum and turn 20, ...",twitter,1,year gon na become mum turn 20 waaaaah,this year i gon na become a mum and turn 20 wa...
4,5,Don't mind me. Just freaking out because Mary-...,twitter,0,mind freaking ashley olsen turned https,do mind me just freaking out because and ashle...
...,...,...,...,...,...,...
8795,8796,Happy Birthday Brandon James. Hope you have a ...,twitter,0,happy birthday brandon james hope fabulous 23r...,happy birthday brandon james hope you have a f...
8796,8797,"@JonBaker At age 50, I remember cheering ""bana...",twitter,0,age 50 remember cheering bananas hollaback girl,at age 50 i remember cheering bananas before h...
8797,8798,Them Springfield mall pictures.. lol. #va #bda...,twitter,1,springfield mall pictures lol va bday 17yearsy...,them springfield mall pictures lol va bday 17y...
8798,8799,@316Andres88 when we turn 18 were going idgaf ...,twitter,0,turn 18 going idgaf nigga road trip https,when we turn 18 were going idgaf where its at ...
8799,8800,@JanielftJano @Janielkawaii Fanmeosmwhskd me w...,twitter,0,fanmeosmwhskd turn 18 get matching tattoos,fanmeosmwhskd me when i turn 18 so we can get ...

In [ ]:
# import pandas as pd
# from sklearn.feature_extraction.text import CountVectorizer

# selected_df = data[['cleaned_text_2', 'label']]

# # Initialize CountVectorizer for bag of ngrams
# ngram_vectorizer = CountVectorizer()  # You can adjust ngram_range as needed

# # Fit and transform the text data
# X_ngrams = ngram_vectorizer.fit_transform(selected_df['cleaned_text_2'])

# # Convert the sparse matrix to a DataFrame
# ngram_df = pd.DataFrame(X_ngrams.toarray(), columns=ngram_vectorizer.get_feature_names_out())

# # Concatenate the label column with the ngram DataFrame
# result_df = pd.concat([ngram_df, selected_df['label']], axis=1)

In [ ]:
# result_df

,000,01,02,02631,03h58m01s,04,05,05h28m02s,05h58m01s,06h28m02s,...,zoltar,zone,zones,zoo,zshop,zumba,zuri,zurich,zwz,label
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8795,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8796,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8797,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8798,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8799,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# result_df.to_csv('/content/drive/MyDrive/Major_Project/Codebase/training/vectorized_labeled.csv', index=False)

In [2]:
data = pd.read_csv('/content/drive/MyDrive/Major_Project/Codebase/training/unlabeled_preprocessed_training.csv', encoding='utf-8')
data

,id,author,title,text,cleaned_text_1,cleaned_text_2
0,bz796p,Scrambles99,Intestinal Issues,I am a young man age 19. Before this illness I...,young man age illness 197 lb 6 0 15 bodyfat mu...,i am a young man age before this illness i was...
1,m7mwkd,KingCeryn,"Neck muscle flexing, possibly Omohyoid, anytim...","29 years old, male, 130 pounds, I have a doc...",29 years old male 130 pounds doctors appointme...,29 years old male 130 pounds i have a doctors ...
2,2mh45q,Mordor_or_bust,29/F Brown urine &amp; flu-like symptoms,About 5 or 6 months ago I became sick with wha...,5 6 months ago became sick seemed like bad sto...,about 5 or 6 months ago i became sick with wha...
3,2fq5mh,yeast-1,Question about anti-fungal creams or lotions,"Age:31. Male. 6'0"", 205#, White, PmHX: HTN (tr...",male 6 0 205 white pmhx htn treated ace inhibi...,male 6 0 205 white pmhx htn treated with ace i...
4,8ihond,Derek800,Elevated Lipase and Amylase,"Hello, I've asked this question on here a lit...",hello asked question little back issue continu...,hello i asked this question on here a little w...
...,...,...,...,...,...,...
99995,gewohl,BlueTipi,Why can't I eat quietly?,People often tell me that I'm a very noisy eat...,people often tell noisy eater try chew slowly ...,people often tell me that i a very noisy eater...
99996,blnbah,plywooddrywall,Red/Purple blotches on pubic area won't go away,I think it all started when I shaved my pubic ...,think started shaved pubic hair short 5 years ...,i think it all started when i shaved my pubic ...
99997,ndql1u,1g0tquestions,Are high testosterone and estrogen a good sign?,Some of the symptoms which I had been experien...,symptoms experiencing fatigue lethargy brain f...,some of the symptoms which i had been experien...
99998,tearhc,Hannah2482,Is a 32F bra size + back pain enough for a bre...,Hi all. So I’m 18F 5’7 142 pounds and I have s...,hi 18f 5 7 142 pounds size breasts feel like p...,hi all so i m 18f 5 7 142 pounds and i have si...
99999,qukw0e,TheBlank_One,"Liver lesions, Mets or nothing?","Hi, 28 y/o male, non smoker, not heavy drinker...",hi 28 male non smoker heavy drinker 2018 diagn...,hi 28 male non smoker not heavy drinker in 201...

In [3]:
null_count = data['cleaned_text_2'].isnull().sum()
null_count

6

In [4]:
column_name = 'cleaned_text_2'  # Specify the column name
data = data.dropna(subset=[column_name])

In [ ]:
# from sklearn.feature_extraction.text import CountVectorizer

# selected_df = data[['cleaned_text_2', 'id']]

# # Initialize CountVectorizer for bag of ngrams
# ngram_vectorizer = CountVectorizer(ngram_range=(3,3))  # You can adjust ngram_range as needed

# # Fit and transform the text data
# X_ngrams = ngram_vectorizer.fit_transform(selected_df['cleaned_text_2'])

# # Convert the sparse matrix to a DataFrame
# ngram_df = pd.DataFrame(X_ngrams.toarray(), columns=ngram_vectorizer.get_feature_names_out())

# # Concatenate the label column with the ngram DataFrame
# # result_df = pd.concat([ngram_df, selected_df['label']], axis=1)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

selected_df = data[['cleaned_text_2', 'id']]

# Initialize CountVectorizer for bag of ngrams
ngram_vectorizer = CountVectorizer()  # You can adjust ngram_range as needed

# Select only the first 10000 rows of the 'cleaned_text_2' column
selected_df_subset = selected_df['cleaned_text_2'][:10000]

# Fit and transform the text data for the subset
X_ngrams_subset = ngram_vectorizer.fit_transform(selected_df_subset)

# Convert the sparse matrix to a DataFrame for the subset
ngram_df_subset = pd.DataFrame(X_ngrams_subset.toarray(), columns=ngram_vectorizer.get_feature_names_out())

ngram_df_subset

,00,000,000lbs,00h30,01,0189,02,020,02h40,03,...,zycam,zygoma,zygomatic,zyprexa,zyrtec,zyrtech,zyrtex,zzquil,zzzquil,zzzzquil
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
ngram_df_subset.to_csv('/content/drive/MyDrive/Major_Project/Codebase/training/vectorized_unlabeled.csv', index=False)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

selected_df = data[['cleaned_text_2', 'id']]

# Initialize CountVectorizer for bag of ngrams
ngram_vectorizer = CountVectorizer()  # You can adjust ngram_range as needed

# Select only the first 10000 rows of the 'cleaned_text_2' column
selected_df_subset = selected_df['cleaned_text_2'][:20000]

# Fit and transform the text data for the subset
X_ngrams_subset = ngram_vectorizer.fit_transform(selected_df_subset)

# Convert the sparse matrix to a DataFrame for the subset
ngram_df_subset = pd.DataFrame(X_ngrams_subset.toarray(), columns=ngram_vectorizer.get_feature_names_out())

ngram_df_subset

# Append the subset DataFrame to the CSV file
ngram_df_subset.to_csv('/content/drive/MyDrive/Major_Project/Codebase/training/vectorized_unlabeled.csv', mode='a', index=False)

In [8]:
result_df = pd.read_csv('/content/drive/MyDrive/Major_Project/Codebase/training/vectorized_unlabeled.csv', encoding='utf-8')

result_df

ParserError: Error tokenizing data. C error: Expected 30421 fields in line 10002, saw 40907

In [ ]:
X_labeled = result_df.iloc[:, :-1]
Y_labeled = result_df.iloc[:, -1]