In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
file_path = '/content/drive/MyDrive/Major_Project/Codebase/validation/labeled_validation.csv'

In [3]:
import pandas as pd
test1 = pd.read_csv(file_path)
df = pd.DataFrame(test1)
df

         id                                               text  source  label
0      8801  Everybody developa cataracts with age. Disease...  reddit      0
1      8802  I have not heard that before. I have ICL's, bu...  reddit      0
2      8803  What does your doctor/fitter say? I sure wish ...  reddit      0
3      8804  Dear doctor of optometrists of the internet I ...  reddit      1
4      8805  If you have sharp vision without correction, p...  reddit      0
...     ...                                                ...     ...    ...
4195  12996  Why can’t people just accept no as an answer! ...  reddit      1
4196  12997  Even the thought of this terrifies me. Im 18 a...  reddit      1
4197  12998  I don't think exposure works for me either. I ...  reddit      0
4198  12999  I'm a 16 year old going into Junior year of hi...  reddit      1
4199  13000  Seeing this girl - Hey guys.   I’m pretty sure...  reddit      1

[4200 rows x 4 columns]

In [4]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

def preprocess_text_with_stop_words(text):
    # Lowercasing: Convert text to lowercase
    text = text.lower()

    # Remove usernames
    text = re.sub(r'@(\w+)', '', text)

    # Tokenization: Split the text into words
    words = nltk.word_tokenize(text)

    # Remove punctuation and non-alphanumeric characters
    words = [word for word in words if re.match(r'^[a-z0-9]+$', word)]

    # Remove English stopwords
    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word not in stop_words]

    # Join the words back into a single string
    preprocessed_text = ' '.join(words)

    return preprocessed_text

def preprocess_text_without_stop_words(text):
    # Lowercasing: Convert text to lowercase
    text = text.lower()

    # Remove usernames
    text = re.sub(r'@(\w+)', '', text)

    # Tokenization: Split the text into words
    words = nltk.word_tokenize(text)

    # Remove punctuation and non-alphanumeric characters
    words = [word for word in words if re.match(r'^[a-z0-9]+$', word)]

    # Join the words back into a single string
    preprocessed_text = ' '.join(words)

    return preprocessed_text

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [5]:
df['cleaned_text_1'] = df['text'].apply(preprocess_text_with_stop_words)
df['cleaned_text_2'] = df['text'].apply(preprocess_text_without_stop_words)

In [6]:
df

,id,text,source,label,cleaned_text_1,cleaned_text_2
0,8801,Everybody developa cataracts with age. Disease...,reddit,0,everybody developa cataracts age diseases like...,everybody developa cataracts with age diseases...
1,8802,"I have not heard that before. I have ICL's, bu...",reddit,0,heard icl artisan toric irisclaw lenses sit fr...,i have not heard that before i have icl but ar...
2,8803,What does your doctor/fitter say? I sure wish ...,reddit,0,say sure wish could wear sclerals 38 40 year o...,what does your say i sure wish i could wear sc...
3,8804,Dear doctor of optometrists of the internet I ...,reddit,1,dear doctor optometrists internet asking advic...,dear doctor of optometrists of the internet i ...
4,8805,"If you have sharp vision without correction, p...",reddit,0,sharp vision without correction please dont ge...,if you have sharp vision without correction pl...
...,...,...,...,...,...,...
4195,12996,Why can’t people just accept no as an answer! ...,reddit,1,people accept answer cant people understand li...,why can t people just accept no as an answer w...
4196,12997,Even the thought of this terrifies me. Im 18 a...,reddit,1,even thought terrifies im 18 know ever able ta...,even the thought of this terrifies me im 18 an...
4197,12998,I don't think exposure works for me either. I ...,reddit,0,think exposure works either volunteer firefigh...,i do think exposure works for me either i was ...
4198,12999,I'm a 16 year old going into Junior year of hi...,reddit,1,16 year old going junior year high school,i a 16 year old going into junior year of high...
4199,13000,Seeing this girl - Hey guys. I’m pretty sure...,reddit,1,seeing girl hey guys pretty sure social anxiet...,seeing this girl hey guys i m pretty sure that...

In [7]:
df.to_csv("/content/drive/MyDrive/Major_Project/Codebase/validation/labeled_preprocessed_validation.csv", index=False)